name: Build and deploy ASP.Net Core app to Azure Web App - ProtectingYourSecretsWeb-20251231acw

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
env:
  DOTNET_VERSION: '8.x'
  SECRET_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_someuniqueidhere }}
  SECRET_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_someuniqueidhere }}
  SECRET_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_someuniqueidhere  }}
  APP_NAME: 'your-app-name-here'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    defaults:
      run:
        working-directory: ./MVCProtectingSecrets
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ env.SECRET_CLIENT_ID }}
          tenant-id: ${{ env.SECRET_TENANT_ID }}
          subscription-id: ${{ env.SECRET_SUBSCRIPTION_ID }}
  
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          package: ${{ env.DOTNET_ROOT }}/myapp
          